### ISSUE TITLE
Blank result generated 

### ISSUE THREAD

**Issue by kexul** [roykapon/MAS#1] opened 2023-11-09 03:33 UTC
Thanks for your great work! 
I've download the pretrained model and try to generate 3D motions by: 
```
python -m sample.mas --model_path save/nba/nba_diffusion_model/checkpoint_500000.pth
```
The process finished without error, with 10 `mp4` files and 1 `npy` file generated in the `nba_diffusion_model/mas_seed_0` directory, but the `mp4` file is blank.  

I've checked the `npy` file, which seems good to me. 
![image](https://github.com/roykapon/MAS/assets/5920217/14ee4286-b7e3-4e08-acb5-b9231fb697f8)

Here is my npy file and one of my mp4 file: 
[Downloads.zip](https://github.com/roykapon/MAS/files/13303450/Downloads.zip)

**Comment by roykapon** [comment] 2023-11-12 10:34
Hi @kexul, thank you for checking out our code!
Unfortunately, I could not reproduce this issue on my machine. It could have something to do with the ffmpeg installation, so please verify that ffmpeg is correctly installed by running `ffmpeg -version` (my version is `4.2.2`). If it is installed, this link might be of some help: https://stackoverflow.com/questions/59953588/matplotlib-why-is-my-saved-animation-video-blank
Alternatively, you could use PillowWriter to save the animation in `.gif` format. For that sake, you can change the function `save_animation` in `utils/plot_script.py` to:
```
def save_animation(anim: FuncAnimation, save_path, fps):
    save_path = f"{save_path}.gif"
    print(f"saving to [{os.path.abspath(save_path)}]...", end="", flush=True)
    writer = PillowWriter(fps=fps)
    anim.save(save_path, writer=writer)
    print("\033[0K\r\033[0K\r", end="")
    print(f"saved to [{os.path.abspath(save_path)}]")
```

Please update us whether it helped you or not :)
We would also like to know if anyone else has experienced similar issues.

**Comment by kexul** [comment] 2023-11-13 10:02
Hi @roykapon , many thanks for your help! 🤗 

> so please verify that ffmpeg is correctly installed by running 

1. I'm using ffmpeg `ffmpeg version 3.4.11-0ubuntu0.1`. Just found that the torchvision bundled ffmpeg is broken, I replaced it with the ubuntu's. https://github.com/pytorch/vision/issues/7508

> Alternatively, you could use PillowWriter to save the animation in .gif format.

2. Nope, it also produces blank .gif file.

**Comment by Dimoyok** [comment] 2024-01-25 12:24
Hello @roykapon (Thank you for the great technology and amazing paper!)  and @kexul.
I had the same problem, but it was solved quite simply. You need to reinstall matplotlib of the right version:
`pip3 install matplotlib==3.1.3`
I hope this helps someone else.

**Comment by roykapon** [comment] 2024-03-06 23:43
Thank you @Dimoyok !! It appears to be the right solution :) So, for now I will be closing this issue, but feel free to let us know if it persists.

**Closed as completed** 2024-03-06 23:43 UTC
